spring.application.name=blood-donor

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/blood_donor?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=${DB_USERNAME:blood_admin}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Session
spring.session.store-type=none

# Application timezone
spring.jackson.time-zone=Asia/Kolkata